### ISSUE TITLE
Errors in code in docs unit cookbook entry

### ISSUE THREAD

**Issue by EGaraldi** [cbyrohl/scida#104]
The code in the [units cookbook](https://cbyrohl.github.io/scida/notebooks/cookbook/units/) does not execute and displays errors.

**Comment by cbyrohl** [comment]
Page is outdated and will be deleted; instead linked new [unit](https://github.com/cbyrohl/scida/blob/main/docs/units.md) in table of contents.

**Comment by cbyrohl** [comment]
Thanks a lot, missed that. Fixed with PR #119
