### ISSUE TITLE
SDSS example uses inaccessible file

### ISSUE THREAD

**Issue by kyleaoman** [cbyrohl/scida#109]
The example with a fits file (SDSS DR16) would be better if the input file was made available - this could be either exposing the current file or choosing a different one that can be made available. (I actually tried to retrieve it from the Munich systems just to see if I could run the example but don't have permission on /virgotng/mpia).

**Comment by cbyrohl** [comment]
Good point. The SDSS DR16 redshift and classification file "specObj-dr16.fits " can be found [here](https://live-sdss4org-dr16.pantheonsite.io/spectro/spectro_access/), please give it a try. Thanks!
