### ISSUE TITLE
Visualization tutorial file access

### ISSUE THREAD

**Issue by kyleaoman** [cbyrohl/scida#111]
The visualization example assumes a `TNG50-1` snapshot as input. A short preamble would be appropriate explaining: (1) how to get this input file (e.g. from the TNG public data release, liking to the relevant webpage), and (2) that the example also works with the `TNG50-4` input file provided for the introductory tutorial.

**Comment by cbyrohl** [comment]
Pages outside of the tutorial subsection are snippets not associated with a certain data set. Ill 1.) change all examples to TNG50-4, and 2.) add an info box making this clearer.
