### ISSUE TITLE
Halo/galaxy catalogue example data

### ISSUE THREAD

**Issue by kyleaoman** [cbyrohl/scida#117]
The examples in the 'Halo and galaxy catalogs' section of the docs would benefit from sample input data, currently the sample snapshot provided does not include a group catalog. It's probably not necessary to directly host the sample data, a clear signposting to the TNG data release, or "this example can be run on a TNG JupyterLab instance" with some brief instructions (assumed working directory?) would suffice. A concrete link between the examples and actual input where they should be expected to work  - I assume they were written with some concrete input for testing - would be beneficial overall.

**Comment by cbyrohl** [comment]
With PR #124 I added a download link for the group catalog and instructions how to fetch and run. Suggestion for linking TNGLab is tracked in #125
