### ISSUE TITLE
API docs incomplete

### ISSUE THREAD

**Issue by kyleaoman** [cbyrohl/scida#118]
The API docs are a bit rough around the edges. For example, there are many parameters without descriptions, these should be filled in as much as possible. Types are also good to have where possible, but omitting these in some cases is reasonable.

There are also a number of empty module (?) entries, such as `MTNG` and `TNGcluster`. These should either be hidden if they are not intended to be documented here, or fully documented here (if work-in-progress, move to a feature branch?).

**Comment by cbyrohl** [comment]
Thanks for the feedback, I addressed the issue in PR #121. First, I moved the automatically generated index from docstrings to [another page](https://cbyrohl.github.io/scida/api/moduleindex/) and started added a more readable basic api page [here](https://cbyrohl.github.io/scida/api/base_api/). This way, we omit non fully documented classes for now, to be potentially added to the basic api page in the future. Second, regarding lack of parameters/types, I added basic docstrings to >80% of all functions/classes/modules.
