### ISSUE TITLE
Link to TNGLab

### ISSUE THREAD

**Issue by cbyrohl** [cbyrohl/scida#125]
We need to include a link and instructions to run on [TNGLab](https://www.tng-project.org/data/forum/topic/742/scida-analysis-toolkit-example-within-tng-lab/).

**Comment by dnelson86** [comment]
Under "Large Datasets" you say "If you want to run the code below, you need access to the full [TNG](https://www.tng-project.org/) simulation dataset."

Here you can just suggest that the easiest way is to use the TNG-Lab.

**Comment by dnelson86** [comment]
On all the other such pages, you say "If you want to run the code below, consider using the demo data as described [here](https://cbyrohl.github.io/scida/supported_datasets/tng/#demo-data)."

You can also suggest the alternate option of using the TNG-Lab, such that you don't have to download anything.

After these updates, can close this issue.
