### ISSUE TITLE
plotting ra,dec from eFEDS FITS file (without units?)

### ISSUE THREAD

**Issue by dnelson86** [cbyrohl/scida#150]
I copied the example code for the SDSS FITS file, for a different file:

```
import matplotlib.pyplot as plt
import numpy as np
import scida

path = '/virgotng/mpia/obs/eROSITA/eFEDS/'
filename = 'fm00_merged_020_EventList_c001.fits'

ds = scida.load(path + filename)

fig = plt.figure(figsize=(10,5))
ax = fig.add_subplot(111, projection="aitoff")
sc = ax.scatter(ds['RA'], ds['DEC'], s=0.05, c=ds['PI'], rasterized=True)
fig.colorbar(sc, label="Photon Energy [eV]")
ax.set_xticklabels(['14h','16h','18h','20h','22h','0h','2h','4h','6h','8h','10h'])
ax.set_xlabel("RA")
ax.set_ylabel("DEC")
ax.grid(True)
plt.savefig("eFEDS.png", dpi=150)
```

which produces the following image:

![eFEDS](https://github.com/cbyrohl/scida/assets/3587498/c32b917f-a54b-447a-bd5b-0a4df902e3f3)

but the distribution of RA,DEC in this file (in theory) are localized to a small sky region like this:

![Footprint-of-eFEDS-given-by-the-black-solid-line-Cluster-candidates-present-in-the](https://github.com/cbyrohl/scida/assets/3587498/727c75e1-94f3-4964-860c-11a983fbbcb7)

Is this possibly because the fields in this FITS file have no units?

```
WARNING:scida.io._base:FITS file support is work-in-progress.
WARNING:scida.interfaces.mixins.units:Cannot determine units from neither unit file nor metadata for '/DEC'.
WARNING:scida.interfaces.mixins.units:Cannot determine units from neither unit file nor metadata for '/PI'.
WARNING:scida.interfaces.mixins.units:Cannot determine units from neither unit file nor metadata for '/RA'.
```

or possibly something else?

**Comment by dnelson86** [comment]
Documentation for the structure of such files:

https://erosita.mpe.mpg.de/dr1/eSASS4DR1/eSASS4DR1_ProductsDescription/extensions_description_dr1.html

**Comment by dnelson86** [comment]
Same result with:

```
sc = ax.scatter(ds['RA']*ds.ureg['deg'], ds['DEC']*ds.ureg['deg'], s=0.05, c=ds['PI'], rasterized=True)

WARNING:pint.util:Calling the getitem method from a UnitRegistry is deprecated. use `parse_expression` method or use the registry as a callable.
WARNING:pint.util:Calling the getitem method from a UnitRegistry is deprecated. use `parse_expression` method or use the registry as a callable.
/u/dnelson/.local/envs/py3/lib/python3.9/site-packages/numpy/ma/core.py:2820: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  _data = np.array(data, dtype=dtype, copy=copy,
/u/dnelson/.local/envs/py3/lib/python3.9/site-packages/matplotlib/axes/_axes.py:4353: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  c = np.asanyarray(c, dtype=float)
```

**Comment by cbyrohl** [comment]
One can test this without units:

``` python
ds = scida.load(path + filename, units=False)
```

which gives the same result except for carrying "unknown units" as a pint.Quantity.

**Comment by dnelson86** [comment]
```
In [5]: RA.min()
Out[5]: 126.20363814596136

In [6]: RA.max()
Out[6]: 145.82010938548257

In [7]: DEC.min()
Out[7]: -3.223283315519501

In [8]: DEC.max()
Out[8]: 6.099576083087285
```

**Comment by dnelson86** [comment]
The result is the same with `ds = scida.load(path + filename, units=False)`.

**Comment by cbyrohl** [comment]
Isn't the computed data range correct?

**Comment by dnelson86** [comment]
Yes, just the visual plot is wrong. Turning off the aitoff projection with `ax = fig.add_subplot(111)` fixes everything, and produces this image:

![eFEDS4](https://github.com/cbyrohl/scida/assets/3587498/1be70bef-5a5f-497d-a2c5-51410415cd49)

Is this just some matplotlib bug, or some strange interaction between scida and matplotlib?

**Comment by cbyrohl** [comment]
It is the same when you pass these arrays cast to numpy, so I do not think this has anything to do with scida.

Regarding units for eFEDS: If there is no metadata, we do not make an assumption for the units here. We can provide a minimal unit file.

**Comment by dnelson86** [comment]
With correct x-axis, and sorting by photon energy:

![eFEDSd](https://github.com/cbyrohl/scida/assets/3587498/6808b526-8b30-41a9-bdce-672081fad4a9)

**Comment by dnelson86** [comment]
All 172M photons of the full eRASS1, unfortunately I think (vs [Merloni+24 Fig 6](https://arxiv.org/pdf/2401.17274.pdf)) it suffers from a similar bug, i.e. the data should not fill the sky:

![eRASS1](https://github.com/cbyrohl/scida/assets/3587498/9035251f-e060-4c01-a1e6-32ce8219910e)

**Comment by cbyrohl** [comment]
Did you check the matplotlib docs? I could imagine it uses radians rather than degrees.

**Comment by dnelson86** [comment]
That's right, 

```
import matplotlib.pyplot as plt
import numpy as np
import scida

path = '/virgotng/mpia/obs/eROSITA/eFEDS/'
filename = 'fm00_merged_020_EventList_c001.fits'

ds = scida.load(path + filename)

fig = plt.figure(figsize=(10,5))
ax = fig.add_subplot(111, projection="aitoff")

ra_rad = ds['RA'] * np.pi/180
dec_rad = ds['DEC'] * np.pi/180
sc = ax.scatter(ra_rad, dec_rad, s=0.05, c=ds['PI'], rasterized=True)
fig.colorbar(sc, label="Photon Energy [eV]")
ax.set_xticklabels(['14h','16h','18h','20h','22h','0h','2h','4h','6h','8h','10h'])
ax.set_xlabel("RA")
ax.set_ylabel("DEC")
ax.grid(True)
plt.savefig("eFEDS.png", dpi=150)
```

correctly produces

![eFEDS](https://github.com/user-attachments/assets/56e9b81a-6a6e-4b89-92ed-9f23078f6ced)

although, interestingly, since `ds['RA']`  has unknown units

```
In [5]: ra = ds['RA'].compute()

In [6]: np.deg2rad(ra).min()
Out[6]: <Quantity(126.203638, 'radian')>

In [7]: np.deg2rad(ra).max()
Out[7]: <Quantity(145.820109, 'radian')>

In [8]: ra.min()
Out[8]: <Quantity(126.203638, 'unknown')>

In [9]: ra.max()
Out[9]: <Quantity(145.820109, 'unknown')>

In [10]: ra
Out[10]:
<Quantity([127.69589399 127.99142376 127.80048536 ... 143.15063796 143.44560777
 143.15305136], 'unknown')>

In [18]: np.deg2rad(ra)
Out[18]:
<Quantity([127.69589399 127.99142376 127.80048536 ... 143.15063796 143.44560777
 143.15305136], 'radian')>

In [24]: np.deg2rad(np.array(ra))
<ipython-input-24-f9cab65db283>:1: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  np.deg2rad(np.array(ra))
Out[24]:
array([2.22871379, 2.23387176, 2.23053926, ..., 2.49844996, 2.50359815,
       2.49849208])
```

i.e. the numpy unit conversion, for some reason, just attaches the radian units and doesn't actually make the conversion, unless the 'unknown' units are first stripped off.
