### ISSUE TITLE
Documentation: tutorial `wget` command needs quotes for its argument

### ISSUE THREAD

**Issue by evertrol** [cbyrohl/scida#156]
Minor thing I ran across while going through the simulation data tutorial:
```
wget https://heibox.uni-heidelberg.de/f/dc65a8c75220477eb62d/?dl=1 -O snapshot.tar.gz
```

will need quotes, as some shells may attempt to match the `?`, and fail with a `no matches found` error.

For example, zsh does this, which is nowadays the default shel on macOS.

Thus:
```
wget "https://heibox.uni-heidelberg.de/f/dc65a8c75220477eb62d/?dl=1" -O snapshot.tar.gz
```

**Comment by cbyrohl** [comment]
Thanks a lot @evertrol, I'll adjust it accordingly.
