### ISSUE TITLE
progressbar when creating dataset virtual file

### ISSUE THREAD

**Issue by dnelson** [cbyrohl/scida#34]
E.g.
```
In [1]: from astrodask import load
In [2]: ds = load("TNG50-1")

In [3]: snap = ds.get_dataset(z=0.0)

In [4]: snap
Out[4]:
```

appears to "hang" for a long time. We need a progress bar here if a cache/virtual file is being created.

**Comment by dnelson86** [comment]
Another example:

```python

from scida import load
ds = load('TNG50-1')
ds[0]
```

seems like a hang, which encourages the user (me) to hit Ctrl+C, such that the result is all messed up. Good to at least print a simple text message in such a case.

**Comment by cbyrohl** [comment]
Do you have a stack trace? Agree we should add a text message upon evaluation of a dataset. 

I am surprised that ds[0], equivalent to ds.get_dataset(0), is stuck given that `test_delay_obj`  from https://github.com/cbyrohl/scida/commit/ce40a1e4ce2f3e4837851fa0c7a1f11354fbf7eb passes, meaning that evaluation should not be triggered yet.

**Comment by cbyrohl** [comment]
In your case, the object is probably not evaluated lazily due to some [ipython pecularity](https://github.com/jupyter/notebook/issues/2014).

```python
File ~/.cache/pypoetry/virtualenvs/scida-J9ngM3zU-py3.9/lib/python3.9/site-packages/IPython/utils/dir2.py:65, in get_real_method(obj, name)
     55 """Like getattr, but with a few extra sanity checks:
     56 
     57 - If obj is a class, ignore everything except class methods
   (...)
     62 Returns the method or None.
     63 """
     64 try:
---> 65     canary = getattr(obj, '_ipython_canary_method_should_not_exist_', None)
     66 except Exception:
     67     return None
```

We should capture this in addition to the print message for this issue.
