### ISSUE TITLE
simulation dataset support

### ISSUE THREAD

**Issue by dnelson86** [cbyrohl/scida#38]
Desired "dataset support", from our previous HedgeDoc.

Simulations:

- [x] TNG (/virgotng/universe/IllustrisTNG/)
- [x] EAGLE ("TNG-like" version on /virgotng/universe/Eagle/)
- [x] EAGLE (original version)
- [x] SIMBA ("TNG-like" version on /virgotng/universe/Simba/)
- [x] SIMBA (original version)
- [x] Illustris (/virgotng/universe/Illustris/)
- [x] TNG-Cluster (/virgotng/mpia/TNG-Cluster/L680n8192TNG/)
- [x] MTNG (/virgotng/mpa/MTNG/)
- [x] FIRE-2 (public simulations, on /virgotng/mpia/FIRE-2/)
- [x] FLAMINGO (for testing (private): /virgotng/mpia/FLAMINGO/, can also infer from SWIFT code)
- [x] Auriga (/vera/ptmp/gc/dnelson/public/auriga_halo6_lvl6/ for example)
- [x] THESAN (public, /virgotng/mpa/Thesan/Thesan-1/)

**Comment by dnelson86** [comment]
I suggest that MTNG and FLAMINGO support, at release, be partial, i.e. minimal.

Both contain exotic types of additional files/lightcones/catalogs/trees which will take time to properly consider, and this isn't necessary for day 1.

**Comment by cbyrohl** [comment]
Added some more unit support in #96 . Generally all these simulations should load in their basic form (snapshot plus optional catalog).
