### ISSUE TITLE
TNG100-2 Snapshot 30 Not accessible (corrupt cache)

### ISSUE THREAD

**Issue by astronerdF** [cbyrohl/scida#94]
Hi Chris!

I am not sure if I am the only one facing this issue, but I am not able to "load" snapshot #30 from the TNG100-2 simulation.

My code and the error are:

```
basePath = "/virgotng/universe/IllustrisTNG/TNG100-2/output"
ds = load(basePath + f"/snapdir_{30:03d}", units=False)
```

```
OSError                                   Traceback (most recent call last)
Cell In[29], line 1
----> 1 ds = load(basePath + f"/snapdir_{30:03d}", units=False)

File /vera/u/fahma/scida/src/scida/convenience.py:280, in load(path, units, unitfile, overwrite, force_class, **kwargs)
    277         if m in mixins:
    278             mixins.remove(m)
--> 280 instance = cls(path, mixins=mixins, **kwargs)
    281 return instance

File /vera/u/fahma/scida/src/scida/interface.py:39, in MixinMeta.__call__(cls, *args, **kwargs)
     37 mixins = kwargs.pop("mixins", None)
     38 newcls = create_MixinDataset(cls, mixins)
---> 39 return type.__call__(newcls, *args, **kwargs)

File /vera/u/fahma/scida/src/scida/interfaces/mixins/cosmology.py:15, in CosmologyMixin.__init__(self, *args, **kwargs)
     13 def __init__(self, *args, **kwargs):
     14     self.metadata = {}
---> 15     super().__init__(*args, **kwargs)
     16     metadata_raw = self._metadata_raw
     17     c = get_cosmology_from_rawmetadata(metadata_raw)

File /vera/u/fahma/scida/src/scida/customs/arepo/dataset.py:137, in ArepoSnapshot.__init__(self, path, chunksize, catalog, **kwargs)
    135         pass  # this string can be set to explicitly disable catalog
...
File h5py/_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File h5py/h5f.pyx:106, in h5py.h5f.open()

OSError: Unable to open file (file is already open for write (may use  to clear file consistency flags))
```

Do you have any idea on how to fix this perhaps?

**Comment by cbyrohl** [comment]
Hard to say. Can you provide the full stacktrace? (expand after  `135         pass  # this string can be set to explicitly disable catalog ...`)

**Comment by astronerdF** [comment]
Apologies, 
This is the full error:

`---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[10], line 2
      1 basePath = "[/virgotng/universe/IllustrisTNG/TNG100-2/output](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/virgotng/universe/IllustrisTNG/TNG100-2/output)"
----> 2 ds = load(basePath + f"[/snapdir_](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/snapdir_){30:03d}", units=False)

File [/vera/u/fahma/scida/src/scida/convenience.py:280](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/vera/u/fahma/scida/src/scida/convenience.py:280), in load(path, units, unitfile, overwrite, force_class, **kwargs)
    277         if m in mixins:
    278             mixins.remove(m)
--> 280 instance = cls(path, mixins=mixins, **kwargs)
    281 return instance

File [/vera/u/fahma/scida/src/scida/interface.py:39](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/vera/u/fahma/scida/src/scida/interface.py:39), in MixinMeta.__call__(cls, *args, **kwargs)
     37 mixins = kwargs.pop("mixins", None)
     38 newcls = create_MixinDataset(cls, mixins)
---> 39 return type.__call__(newcls, *args, **kwargs)

File [/vera/u/fahma/scida/src/scida/interfaces/mixins/cosmology.py:15](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/vera/u/fahma/scida/src/scida/interfaces/mixins/cosmology.py:15), in CosmologyMixin.__init__(self, *args, **kwargs)
     13 def __init__(self, *args, **kwargs):
     14     self.metadata = {}
---> 15     super().__init__(*args, **kwargs)
     16     metadata_raw = self._metadata_raw
     17     c = get_cosmology_from_rawmetadata(metadata_raw)

File [/vera/u/fahma/scida/src/scida/customs/arepo/dataset.py:137](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/vera/u/fahma/scida/src/scida/customs/arepo/dataset.py:137), in ArepoSnapshot.__init__(self, path, chunksize, catalog, **kwargs)
    135         pass  # this string can be set to explicitly disable catalog
    136     elif self.catalog is not None:
--> 137         self.load_catalog(kwargs)
    139 # add aliases
    140 aliases = dict(
    141     PartType0=["gas", "baryons"],
    142     PartType1=["dm", "dark matter"],
   (...)
    146     PartType5=["bh", "black holes"],
    147 )

File [/vera/u/fahma/scida/src/scida/customs/arepo/dataset.py:183](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/vera/u/fahma/scida/src/scida/customs/arepo/dataset.py:183), in ArepoSnapshot.load_catalog(self, kwargs)
    180 if hasattr(self, "ureg"):
    181     ureg = self.ureg
--> 183 self.catalog = cls(
    184     self.catalog,
    185     virtualcache=virtualcache,
    186     fileprefix=prfx,
    187     units=self.withunits,
    188     ureg=ureg,
    189 )
    190 if "Redshift" in self.catalog.header and "Redshift" in self.header:
    191     z_catalog = self.catalog.header["Redshift"]

File [/vera/u/fahma/scida/src/scida/interface.py:39](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/vera/u/fahma/scida/src/scida/interface.py:39), in MixinMeta.__call__(cls, *args, **kwargs)
     37 mixins = kwargs.pop("mixins", None)
     38 newcls = create_MixinDataset(cls, mixins)
---> 39 return type.__call__(newcls, *args, **kwargs)

File [/vera/u/fahma/scida/src/scida/interfaces/mixins/cosmology.py:15](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/vera/u/fahma/scida/src/scida/interfaces/mixins/cosmology.py:15), in CosmologyMixin.__init__(self, *args, **kwargs)
     13 def __init__(self, *args, **kwargs):
     14     self.metadata = {}
---> 15     super().__init__(*args, **kwargs)
     16     metadata_raw = self._metadata_raw
     17     c = get_cosmology_from_rawmetadata(metadata_raw)

File [/vera/u/fahma/scida/src/scida/customs/arepo/dataset.py:628](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/vera/u/fahma/scida/src/scida/customs/arepo/dataset.py:628), in ArepoCatalog.__init__(self, *args, **kwargs)
    626 if "fileprefix" not in kwargs:
    627     kwargs["fileprefix"] = "groups"
--> 628 super().__init__(*args, **kwargs)

File [/vera/u/fahma/scida/src/scida/customs/arepo/dataset.py:127](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/vera/u/fahma/scida/src/scida/customs/arepo/dataset.py:127), in ArepoSnapshot.__init__(self, path, chunksize, catalog, **kwargs)
    125 if prfx is None:
    126     prfx = self._get_fileprefix(path)
--> 127 super().__init__(path, chunksize=chunksize, fileprefix=prfx, **kwargs)
    129 self.catalog = catalog
    130 if not self.iscatalog:

File [/vera/u/fahma/scida/src/scida/interfaces/mixins/spatial.py:22](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/vera/u/fahma/scida/src/scida/interfaces/mixins/spatial.py:22), in SpatialCartesian3DMixin.__init__(self, *args, **kwargs)
     20 def __init__(self, *args, **kwargs):
     21     self.hints = {}
---> 22     super().__init__(*args, **kwargs)
     23     # TODO: determine whether periodic?
     24     self.pbc = True

File [/vera/u/fahma/scida/src/scida/customs/gadgetstyle/dataset.py:20](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/vera/u/fahma/scida/src/scida/customs/gadgetstyle/dataset.py:20), in GadgetStyleSnapshot.__init__(self, path, chunksize, virtualcache, **kwargs)
     17 """We define gadget-style snapshots as nbody/hydrodynamical simulation snapshots that follow
     18 the common [/PartType0](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/PartType0), [/PartType1](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/PartType1) grouping scheme."""
     19 self.boxsize = np.nan
---> 20 super().__init__(path, chunksize=chunksize, virtualcache=virtualcache, **kwargs)
     22 defaultattributes = ["config", "header", "parameters"]
     23 for k in self._metadata_raw:

File [/vera/u/fahma/scida/src/scida/interface.py:82](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/vera/u/fahma/scida/src/scida/interface.py:82), in BaseDataset.__init__(self, path, chunksize, virtualcache, overwritecache, fileprefix, hints, **kwargs)
     71     raise Exception("Specified path '%s' does not exist." % self.path)
     73 loadkwargs = dict(
     74     overwrite=self.overwritecache,
     75     fileprefix=fileprefix,
   (...)
     79     withunits=self.withunits,
     80 )
---> 82 res = scida.io.load(path, **loadkwargs)
     83 self.data = res[0]
     84 self._metadata_raw = res[1]

File [/vera/u/fahma/scida/src/scida/io.py:420](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/vera/u/fahma/scida/src/scida/io.py:420), in load(path, **kwargs)
    418 def load(path, **kwargs):
    419     loader = determine_loader(path, **kwargs)
--> 420     data, metadata = loader.load(**kwargs)
    421     file = loader.file
    422     tmpfile = loader.tempfile

File [/vera/u/fahma/scida/src/scida/io.py:162](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/vera/u/fahma/scida/src/scida/io.py:162), in ChunkedHDF5Loader.load(self, overwrite, fileprefix, token, chunksize, virtualcache, **kwargs)
    155     self.create_cachefile(
    156         fileprefix=fileprefix,
    157         virtualcache=virtualcache,
    158         verbose=print_cachefile_creation,
    159     )
    161 try:
--> 162     datadict = self.load_cachefile(
    163         cachefp, token=token, chunksize=chunksize, **kwargs
    164     )
    165 except InvalidCacheError:
    166     # if we get an error, we try to create a new cache file (once)
    167     log.info("Invalid cache file, attempting to create new one.")

File [/vera/u/fahma/scida/src/scida/io.py:219](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/vera/u/fahma/scida/src/scida/io.py:219), in ChunkedHDF5Loader.load_cachefile(self, location, token, chunksize, **kwargs)
    218 def load_cachefile(self, location, token="", chunksize="auto", **kwargs):
--> 219     self.file = h5py.File(location, "r")
    220     hf = self.file
    221     cache_valid = False

File [~/conda-envs/myenv/lib/python3.10/site-packages/h5py/_hl/files.py:567](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/u/fahma/Test/Final%202/~/conda-envs/myenv/lib/python3.10/site-packages/h5py/_hl/files.py:567), in File.__init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, fs_strategy, fs_persist, fs_threshold, fs_page_size, page_buf_size, min_meta_keep, min_raw_keep, locking, alignment_threshold, alignment_interval, meta_block_size, **kwds)
    558     fapl = make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0,
    559                      locking, page_buf_size, min_meta_keep, min_raw_keep,
    560                      alignment_threshold=alignment_threshold,
    561                      alignment_interval=alignment_interval,
    562                      meta_block_size=meta_block_size,
    563                      **kwds)
    564     fcpl = make_fcpl(track_order=track_order, fs_strategy=fs_strategy,
    565                      fs_persist=fs_persist, fs_threshold=fs_threshold,
    566                      fs_page_size=fs_page_size)
--> 567     fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
    569 if isinstance(libver, tuple):
    570     self._libver = libver

File [~/conda-envs/myenv/lib/python3.10/site-packages/h5py/_hl/files.py:231](https://vscode-remote+ssh-002dremote-002bvera2.vscode-resource.vscode-cdn.net/u/fahma/Test/Final%202/~/conda-envs/myenv/lib/python3.10/site-packages/h5py/_hl/files.py:231), in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    229     if swmr and swmr_support:
    230         flags |= h5f.ACC_SWMR_READ
--> 231     fid = h5f.open(name, flags, fapl=fapl)
    232 elif mode == 'r+':
    233     fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

File h5py/_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py/_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File h5py/h5f.pyx:106, in h5py.h5f.open()

OSError: Unable to open file (file is already open for write (may use  to clear file consistency flags))`

**Comment by cbyrohl** [comment]
Thanks a lot. Seems like the cache file for this snapshot is corrupted, deleting it would fix the issue. Not sure what is the best way to find its path. Let me provide a fix later.

**Comment by dnelson86** [comment]
Always seems possible that a cache file will be corrupted, e.g. due to a `Ctrl+C` midway through its creation.

We already handle this for series caches, is that right?

Just wrap such usage in a `try`, and for any error, attempt (once) to recreate the relevant cache?

**Comment by cbyrohl** [comment]
> Always seems possible that a cache file will be corrupted, e.g. due to a Ctrl+C midway through its creation.
> We already handle this for series caches, is that right?
> Just wrap such usage in a try, and for any error, attempt (once) to recreate the relevant cache?

We already handle snapshot loads with a try. We have been a bit cautious with the Exceptions that trigger the reconstruction (in the except statement), so it is just about widening the exception to include the Exception above. I'll fix it later today.

**Comment by cbyrohl** [comment]
By the way, `load(..., overwritecache=True)` might be a work around in the mean time for such cases.

**Comment by astronerdF** [comment]
Okay, thank you.
