### ISSUE TITLE
Filename in Tutorial->simulations

### ISSUE THREAD

**Issue by EGaraldi** [cbyrohl/scida#98]
The code snippet and sample outputs in the [simulation tutorial](https://cbyrohl.github.io/scida/tutorial/simulations/) do not match the one obtained following the [link](https://heibox.uni-heidelberg.de/f/dc65a8c75220477eb62d/) provided in the same page. The former is "TNG50-4_snapshot" while the latter is "snapdir_030". Similarly, the content of the file is slightly different than showed in the tutorial page. If possible, homogenize them for clarity.

**Comment by kyleaoman** [comment]
Likewise the projection image from the example file differs a bit from the one in the documentation.

**Comment by cbyrohl** [comment]
Thanks @EGaraldi, non standard name dropped in favor of folder name "snapdir_030" in #126 . Thanks @kyleaoman, field reference and projection image adjusted in #114
